version: "3.5"

services:
      
  website:
    image: adejonghm/petclinic:latest
    # build: .
    restart: always
    ports:
      - 8090:8080
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - net-backend
    depends_on:
      - server-db

  server-db:
    image: mysql:5.7
    container_name: server-db
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - petclinic-data:/var/lib/mysql
    networks:
      - net-backend

volumes:
  petclinic-data:
    driver: local

networks:
  net-backend: