version: "3.5"

services:
  Jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports: 
      - 8080:8080
      - 50000:50000
    volumes: 
      - jenkins-home:/var/jenkins_home
    user: root
    privileged: true
    restart: always

volumes:
  jenkins-home:
    driver: local
